### PR TITLE
Update Cargo.lock

### PR DESCRIPTION
**Pull request by ducaale**
This PR also raises MSRV to 1.70 and removes ~once_cell~ `atty` from dependencies.

### CODE REVIEW

**Comment by blyxxyz** [comment]
Perhaps we can also move from `regex` to [`regex-lite`](https://crates.io/crates/regex-lite)? Saves 250 KB, all the tests still pass. (It has a MSRV of 1.65 though.)

All of our regexes seem to run at most once per process on a small haystack, so it shouldn't have any performance impact. (We probably don't even get any performance benefit from that `regex!()` macro outside of tests.)

**Comment by blyxxyz** [comment]
Can't we remove `once_cell` as well?

**Comment by ducaale** [comment]
Yeah, I wanted to do that, but then I noticed that `once_cell` is a transitive dependency of both `reqwest` and `syntext`.

**Comment by blyxxyz** [comment]
Ah, I see. Probably a matter of time until they get rid of it but there's no hurry then.

**Review by blyxxyz — APPROVED** [review]

**Pull request merged**
