### PR TITLE
Introduce clippy and fmt in CI

### LINKED ISSUE #71: Include 'cargo fmt' and 'cargo clippy' in the CI pipeline

### PR DESCRIPTION
**Pull request by ducaale**
Resolves #71

### CODE REVIEW

**Comment by jihchi** [comment]
@ducaale would it be better if we can run the test not only on Linux but also macOS and Windows?

**Comment by ducaale** [comment]
It seems `httpmock` depends on OpenSSL which prevents tests from being run for `x86_64-unknown-linux-musl`. I will see what I can do about it.

**Comment by blyxxyz** [comment]
Is using `cross` necessary? Seems like OpenSSL wouldn't be a problem if the builds ran natively.

**Comment by ducaale** [comment]
It seems https://github.com/trishume/syntect is breaking if `cross` is not enabled 😬. Syntect has `fancy-regex` regex engine which is written in pure Rust but it is slower than the default configuration.

**Comment by ducaale** [comment]
It seems that another C library binding is now failing. Maybe we should focus on OpenSSL problems instead?

re-enabling `onig` now...

**Comment by blyxxyz** [comment]
All I see is `Failed to find tool. Is musl-gcc installed?`. Could that be fixed by installing `musl-tools`?

**Comment by blyxxyz** [comment]
Hm, I think the `arm-unknown-linux-gnueabihf` is running on a `x86_64-unknown-linux-gnu` host.

**Comment by ducaale** [comment]
From reading https://github.com/sfackler/rust-openssl/issues/603, it appears https://github.com/clux/muslrust could help us with OpenSSL for musl?

And here is the github action version https://github.com/zhxiaogg/cargo-static-build

**Comment by ducaale** [comment]
Right, I was using https://github.com/sharkdp/bat/blob/master/.github/workflows/CICD.yml as a reference but somehow copied the wrong target 🤦🏻‍♂️.

**Comment by blyxxyz** [comment]
Testing on musl is difficult, but maybe we could do a simple build on musl (without tests, so no OpenSSL)?

I guess Github Actions doesn't support running on ARM? That makes things difficult. But since it's complaining about OpenSSL, and running ARM binaries would be tricky even if we do compile them, maybe we could also do a testless build for that?

I had to do 5bc653c608cfc90da56fc7efec553a11db169577 to get the Windows pipeline to pass. I can look into a better fix for that later.

**Review by blyxxyz — APPROVED** [review]
Most of the commits should probably be squashed

**Pull request merged**
