### PR TITLE
Change to use Trust-DNS as DNS resolver

### PR DESCRIPTION
**Pull request by sorairolake**
[Trust-DNS](https://github.com/bluejekyll/trust-dns) is based on Rust.

### CODE REVIEW

**Comment by blyxxyz** [comment]
What advantages would this give?

**Comment by sorairolake** [comment]
@blyxxyz I think it is safer than the default DNS resolver using `getaddrinfo()`.

**Comment by blyxxyz** [comment]
If it behaves differently from the normal resolver then that could be confusing. And this adds almost a megabyte to the binary size, even after stripping, so I don't think it's worth it.

**Comment by sorairolake** [comment]
@blyxxyz I understand. Stop changing DNS resolver.

**Pull request closed without merging**
