### PR TITLE
Replace ansi_term by termcolor

### PR DESCRIPTION
**Pull request by blyxxyz**
This required a refactoring which happened to simplify the code somewhat.

I think it's good as is, but I'd like to write some tests. Coloring in general is undertested.

See #98.

### CODE REVIEW

**Comment by blyxxyz** [comment]
I don't have a system to test it, but I'm worried that this breaks the solarized theme in some Windows terminals because `colorterm` prefers the console API even if ANSI formatting is available. (If so, I wonder if they also can't handle `rg --colors match:fg:0,128,255`.)

We might have to force ANSI formatting if a theme requires it. And perhaps bring back `ansi_term` just for `enable_ansi_support()`.

**Comment by ducaale** [comment]
>If so, I wonder if they also can't handle rg --colors match:fg:0,128,255

Screenshot 2021-03-14 223527

**Comment by blyxxyz** [comment]
Thank you, that's reassuring.

> The only defect I noticed so far is that foreground color is not reset when `xh` exits

Aha, I didn't add `buffer.reset()` everywhere that needs it.

**Review by ducaale — APPROVED** [review]
Approved 🎉🎉

**Pull request merged**
