### PR TITLE
Support forcing ipv4/ipv6

### LINKED ISSUE #274: Feature request: support forcing ipv4/ipv6
`cURL` supports `-4`/`--ipv4` and `-6`/`--ipv6` flags. Quoting the `curl(1)` manpage:

``` text
       -4, --ipv4
              This option tells curl to resolve names to IPv4 addresses only, and
              not for example try IPv6.

              Example:
               curl --ipv4 https://example.com

              See also --http1.1 and --http2. This option overrides -6, --ipv6.

       -6, --ipv6
              This option tells curl to resolve names to IPv6 addresses only, and
              not for example try IPv4.

              Example:
               curl --ipv6 https://example.com

              See also --http1.1 and --http2. This option overrides -4, --ipv4.
```

For testing purposes, having this feature would be really convenient.

### PR DESCRIPTION
**Pull request by zuisong**
Resolves #274

### CODE REVIEW

**Comment by zuisong** [comment]
- [ ] unit test
- [ ] local test

**Comment by zuisong** [comment]
https://github.com/ducaale/xh/issues/274

**Comment by zuisong** [comment]
I will reopen this PR when it is ready to merge

**Comment by ducaale** [comment]
Can you branch-off from `develop` instead of `master` and also add `Resolves #274` as a description for the PR? Thanks

**Comment by zuisong** [comment]
> Can you branch-off from `develop` instead of `master` and also add `Resolves #274` as a description for the PR? Thanks

It updated now. Please review it again. 😄

**Pull request closed without merging**
