### PR TITLE
support zstd formatted responses

### PR DESCRIPTION
**Pull request by zuisong**
Chrome versions after 123 already support zstd.  ([can i use zstd](https://caniuse.com/zstd))
Firefox will support zstd https://github.com/mozilla/standards-positions/issues/775#issuecomment-2049605786

Maybe we should also support zstd formatted responses.

image

---

- curl support zstd response
	```
	❯ curl --header 'accept-encoding:zstd'  --compressed https://www.facebook.com/data/manifest/
	{"gcm_sender_id":"15057814354","gcm_user_visible_only":true,"edge_side_panel":{"preferred_width":376},"short_name":"Facebook","name":"Facebook","start_url":"\/?ref=homescreenpwa","display":"minimal-ui","background_color":"#FFFFFF","theme_color":"#1877F2","icons":[{"src":"https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3\/y0\/r\/eFZD1KABzRA.png","sizes":"192x192","type":"image\/png"},{"src":"https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3\/yd\/r\/DeNyZD1Vj3q.png","sizes":"512x512","type":"image\/png"}],"widgets":[{"name":"Facebook","description":"Facebook","short_name":"Facebook","tag":"fb_widget","type":"application\/json","update":100,"icons":[{"src":"https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3\/y0\/r\/eFZD1KABzRA.png","sizes":"192x192"}],"screenshots":[{"src":"https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3\/yT\/r\/mqlhqxHpT-X.png","sizes":"464x478","label":"Widget Screenshot"}],"template":"dummy","data":"\/dummy.json","ms_ac_template":"\/dummy.json"}],"related_applications":[{"platform":"play","id":"com.facebook.katana"},{"platform":"play","id":"com.facebook.lite"},{"platform":"play","id":"com.facebook.orca"},{"platform":"play","id":"com.facebook.mlite"}],"prefer_related_applications":false}⏎                                                                 
	```

---

- xh current
	```
	❯ xh https://www.facebook.com/data/manifest/ accept-encoding:zstd -b
	+-----------------------------------------+
	| NOTE: binary data not shown in terminal |
	+-----------------------------------------+
	```
- after
	```
	❯ cargo run -- https://www.facebook.com/data/manifest/ accept-encoding:zstd -b --pretty=none
	    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
	     Running `/Users/chen/.rust-target/debug/xh 'https://www.facebook.com/data/manifest/' 'accept-encoding:zstd' -b --pretty=none`
	{"gcm_sender_id":"15057814354","gcm_user_visible_only":true,"edge_side_panel":{"preferred_width":376},"short_name":"Facebook","name":"Facebook","start_url":"\/?ref=homescreenpwa","display":"minimal-ui","background_color":"#FFFFFF","theme_color":"#1877F2","icons":[{"src":"https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3\/y0\/r\/eFZD1KABzRA.png","sizes":"192x192","type":"image\/png"},{"src":"https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3\/yd\/r\/DeNyZD1Vj3q.png","sizes":"512x512","type":"image\/png"}],"widgets":[{"name":"Facebook","description":"Facebook","short_name":"Facebook","tag":"fb_widget","type":"application\/json","update":100,"icons":[{"src":"https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3\/y0\/r\/eFZD1KABzRA.png","sizes":"192x192"}],"screenshots":[{"src":"https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3\/yT\/r\/mqlhqxHpT-X.png","sizes":"464x478","label":"Widget Screenshot"}],"template":"dummy","data":"\/dummy.json","ms_ac_template":"\/dummy.json"}],"related_applications":[{"platform":"play","id":"com.facebook.katana"},{"platform":"play","id":"com.facebook.lite"},{"platform":"play","id":"com.facebook.orca"},{"platform":"play","id":"com.facebook.mlite"}],"prefer_related_applications":false}
	```

### CODE REVIEW

**Comment by blyxxyz** [comment]
I'm unsure about this. It'd add another 150KB to the binary (pushing us over 8MB). And I don't know how much upside there is. In which cases would somebody really need it or be helped by it? (In download mode we don't even enable compression.)

I'm also worried about whether this can dynamically link to the system's libzstd, since that's how (some) distros prefer to work. `openssl-sys` has some cargo features related to this but I don't see that in `zstd-sys`. I don't really know the details about how this is normally handled and what `-sys` packages tend to do but it might be a headache (or just busywork) for distro maintainers.

(The `ruzstd` crate could potentially help with both of these but I don't know how mature it is.)

The code does look good.

**Review by ducaale — APPROVED** [review]
Looks good!

@blyxxyz is there anything to change before we merge this PR?

**Review by blyxxyz — APPROVED** [review]
Looks like the right way to do it. I'm still a little worried about the binary size but it is nice to keep up with browsers.

**Comment by Suliat232** [comment]
Looks like right way

**Pull request merged**
